/*
 * Header file to define configurable values within the whole project
 *(e.g. ORBIT_SPEED)
 */

#ifndef CONFIG_H
#define CONFIG_H

// Light Sensors

#define LS_CALIBRATION_COUNT 10
#define LS_CALIBRATION_BUFFER 50

#define LS_MOVEMENT_ANGLE_BUFFER 5
#define LS_MOVEMENT_SMALL_MULTIPLIER 0.5

// Light Gate

#define LIGHT_GATE_CALIBRATION_COUNT 10
#define LIGHT_GATE_CALIBRATION_BUFFER 10

// TSOPS

#define TSOP_NUM 24

#define TSOP_LOOP_COUNT 255

#define TSOP_UNLOCK_DELAY 2

#define TSOP_BEST_TSOP_NO_ANGLE 5
#define TSOP_BEST_TSOP_NO_STRENGTH 2

#define TSOP_K1 10
#define TSOP_K2 2
#define TSOP_K3 1

#define TSOP_MIN_IGNORE 50
#define TSOP_MAX_IGNORE 220

#define TSOP_FIRST_TSOP_WEIGHT 3
#define TSOP_SECOND_TSOP_WEIGHT 2

#define TSOP_FILTER_NOISE true
#define TSOP_FILTER_SURROUNDING true

#define TSOP_NO_BALL 400

// SPI

#define DATA_LENGTH_TSOP 1
#define DATA_LENGTH_LIGHT 1

#define SPI_TSOP_ANGLE 1
#define SPI_TSOP_SPEED 2

// IMU

#define CORRECTION_ROTATION_MINIMUM 5
#define CORRECTION_ROTATION_MAXIMUM 200

#define CORRECTION_ROTATION_MULTIPLIER 1.5

#define IMU_CALIBRATION_COUNT 10
#define IMU_THRESHOLD 5

#define MPU9250_ADDRESS 0x68
#define MAG_ADDRESS 0x0C

#define GYRO_FULL_SCALE_250_DPS 0x00
#define GYRO_FULL_SCALE_500_DPS 0x08
#define GYRO_FULL_SCALE_1000_DPS 0x10
#define GYRO_FULL_SCALE_2000_DPS 0x18

#define ACC_FULL_SCALE_2_G 0x00
#define ACC_FULL_SCALE_4_G 0x08
#define ACC_FULL_SCALE_8_G 0x10
#define ACC_FULL_SCALE_16_G 0x18

// Orbit

#define ORBIT_SHORT_STRENGTH 125
#define ORBIT_BIG_STRENGTH 115

#define ORBIT_SMALL_ANGLE 10
#define ORBIT_BIG_ANGLE 15

#define MIN_ORBIT_SPEED 255
#define MAX_ORBIT_SPEED 127

#define BALL_FRONT_BUFFER 10

// Pixy

#define GOAL_HEIGHT_SHORT 120
#define GOAL_HEIGHT_LONG 20
#define GOAL_DISTANCE_MULTIPLIER 100

// Debug

#define DEBUG_APP_IMU false

#endif // CONFIG_H
